---
title: "CP Analysis Report: US Census Bureau Analysis"
subtitle: "Stat 184"
author:
  - name: Blake Naluai
  - name: Raj Ramnani
date: "Apr. 24, 2026"
date-modified: now

format: pdf

# add bib and csl info if needed on quarto document
# bibliography: temp.bib
# csl: apa.csl
---

{{< pagebreak >}}

## Introduction

The U.S. Census Bureau provides some of the most widely used public data for understanding demographic, economic, and social change in the United States. For this project, we use data accessed through the `{tidycensus}` package in R to examine how selected county-level indicators changed in Maryland around the COVID-19 period, especially from 2019 to 2022. This period is important because it includes major disruptions to work, commuting, income, housing, and household behavior.

Our analysis focuses on Maryland counties using American Community Survey (ACS) 1-year and 5-year estimates, as well as the Decennial Census. We use this information to make tables, plots, and narratives explaining some of the changes that have appeared in the state, and across its counties. 

## Data Provenance:

In this analysis project, we will be working with the \{tidycensus\} package in R. This package in R is designed to make it easy to access US Census data. Firstly, it connects directly to the US Census Bureau API with and API Key given directly to you by the US Census Bureau. Using that key, it will return data in a format that is compatible with \{tidyverse\}. (i.e data frames that can be wrangled, cleaned, and easily used for data analysis). 

### Where the data comes from: 

All data accessed through \{tidycensus\} comes from the following:

**Decennial Census**

- Conducted every 10 years (e.g., 2010, 2020)
- Attempts to count every person in the U.S.
- Collects basic info: age, sex, race, household relationships, etc

**American Community Survey (ACS)**

- A continuous survey
- Provides detailed socioeconomic data of the US

### Who collected it?

The US Census Bureau (Department of Commerce)

### Why was it collected?

- Allocate federal funding
- Determine political representation
- Support research, planning, and policy decisions

### How is it collected?

**Decennial Census**

- Mail forms, online responses, in-person follow-ups
- Aims for a complete count

**American Community Survey (ACS)**

- Uses sampling, not a full count
- About 3–3.5 million households per year are surveyed (randomly selected)

Random sampling survey techniques include:

- mail surveys
- phone interviews
- in-person follow-ups

### When was it collected?

**Decennial Census**

- Every 10 years (i.e 2020)

**American Community Survey (ACS)**

- Conducted continuously every year since 2005
- Data is released as 1-year estimates (large populations) or 5-year estimates (smaller, more reliable populations)

For this analysis, we will be using the American Community Survey (ACS) data from the US Census Bureau to answer the following question(s):

- How did key demographic and economic indicators (such as population, median income, and employment) change across Maryland between 2019 and 2022?
- How did population size and density change across counties surrounding St.Marys, MD between 2019 and 2022?

{{< pagebreak >}}

## Data Tables/Visualizations:

{{< pagebreak >}}

## Data Analysis:

{{< pagebreak >}}

## Code Appendix
```{r}
#| label: codeAppend
#| ref-label: !expr knitr::all_labels()
#| echo: true
#| eval: false

```